url: "https://ian-boraks.github.io"
baseurl: ""

remote_theme: pages-themes/time-machine
plugins:
   - jekyll-remote-theme # add this line to the plugins list if you already have one

title: "Ian Boraks"
name: "Ian Boraks"
tagline: "Ian Boraks"
author: "Ian Boraks"

exclude:
  - LICENSE
  - README.md